name: ci

on:
  push:
    branches:
      - 'feature/Dockerize-With-File-Watch'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:  
      - name: Install GitVersion 
        uses: gittools/actions/gitversion/setup@v0.10.2 
        with:
          versionSpec: '5.x'

      - name: Run GitVersion 
        uses: gittools/actions/gitversion/execute@v0.10.2 
        with: 
          useConfigFile: true 
          #configFilePath: './GitVersion.yml'
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dickwolff/export-to-ghostfolio:latest ${{ env.GitVersion_FullSemVer }}
